[package]
name = "ethrex-crypto"
version.workspace = true
edition.workspace = true
authors.workspace = true
documentation.workspace = true

[lib]
path = "./lib.rs"

[dependencies]
# TODO(#1102): Move to Lambdaworks in the future
c-kzg = { version = "2.1.1", default-features = false, optional = true }
kzg-rs.workspace = true
ethereum-types.workspace = true
getrandom = "0.2.16"
openvm-kzg = { git = "https://github.com/axiom-crypto/openvm-kzg.git", rev = "530a6ed413def5296b7e4967650ba4fc8fd92ea1", optional = true } # v1.4.1
secp256k1.workspace = true
slh-dsa = "0.2.0-rc.1"
thiserror.workspace = true

#[target.'cfg(not(any(target_arch = "x86_64", target_arch = "aarch64")))'.dependencies]
tiny-keccak = { version = "2.0.2", features = ["keccak"] }

[features]
default = []
c-kzg = ["c-kzg/std", "c-kzg/ethereum_kzg_settings"]
openvm-kzg = ["dep:openvm-kzg"]

risc0 = ["c-kzg/std", "c-kzg/ethereum_kzg_settings", "c-kzg/portable"]
openvm = ["openvm-kzg"]

[lints]
workspace = true
